<?php

/**
 * Implementation of hook_uuid_features_default_terms().
 */
function piropublic_uuid_features_default_terms() {
  $terms = array();

  $terms[] = array(
    'uuid' => 'f76d7a2e-ce94-11e0-b44a-9f094f73513e',
    'name' => '3rd Parties',
    'description' => '',
    'weight' => '0',
    'uuid_vocabulary' => 'f768ce04-ce94-11e0-b44a-9f094f73513e',
  );
  $terms[] = array(
    'uuid' => 'f76d9b15-ce94-11e0-b44a-9f094f73513e',
    'name' => 'Action Item',
    'description' => '',
    'weight' => '1',
    'uuid_vocabulary' => 'f768ce04-ce94-11e0-b44a-9f094f73513e',
  );
  $terms[] = array(
    'uuid' => 'f76db87a-ce94-11e0-b44a-9f094f73513e',
    'name' => 'Audit the Fed',
    'description' => '',
    'weight' => '2',
    'uuid_vocabulary' => 'f768ce04-ce94-11e0-b44a-9f094f73513e',
  );
  $terms[] = array(
    'uuid' => 'f76dd029-ce94-11e0-b44a-9f094f73513e',
    'name' => 'Campaign for Liberty',
    'description' => '',
    'weight' => '3',
    'uuid_vocabulary' => 'f768ce04-ce94-11e0-b44a-9f094f73513e',
  );
  $terms[] = array(
    'uuid' => 'f76de776-ce94-11e0-b44a-9f094f73513e',
    'name' => 'Civil Liberties',
    'description' => '',
    'weight' => '4',
    'uuid_vocabulary' => 'f768ce04-ce94-11e0-b44a-9f094f73513e',
  );
  $terms[] = array(
    'uuid' => 'f76dffcd-ce94-11e0-b44a-9f094f73513e',
    'name' => 'Commodities',
    'description' => '',
    'weight' => '5',
    'uuid_vocabulary' => 'f768ce04-ce94-11e0-b44a-9f094f73513e',
  );
  $terms[] = array(
    'uuid' => 'f76e1482-ce94-11e0-b44a-9f094f73513e',
    'name' => 'Congress',
    'description' => '',
    'weight' => '6',
    'uuid_vocabulary' => 'f768ce04-ce94-11e0-b44a-9f094f73513e',
  );
  $terms[] = array(
    'uuid' => 'f76e25d9-ce94-11e0-b44a-9f094f73513e',
    'name' => 'Current Events',
    'description' => '',
    'weight' => '7',
    'uuid_vocabulary' => 'f768ce04-ce94-11e0-b44a-9f094f73513e',
  );
  $terms[] = array(
    'uuid' => 'f76e3a0e-ce94-11e0-b44a-9f094f73513e',
    'name' => 'Democratic Party',
    'description' => '',
    'weight' => '8',
    'uuid_vocabulary' => 'f768ce04-ce94-11e0-b44a-9f094f73513e',
  );
  $terms[] = array(
    'uuid' => 'f76e4f0d-ce94-11e0-b44a-9f094f73513e',
    'name' => 'Domestic Policy',
    'description' => '',
    'weight' => '9',
    'uuid_vocabulary' => 'f768ce04-ce94-11e0-b44a-9f094f73513e',
  );
  $terms[] = array(
    'uuid' => 'f76e6498-ce94-11e0-b44a-9f094f73513e',
    'name' => 'Economy',
    'description' => '',
    'weight' => '10',
    'uuid_vocabulary' => 'f768ce04-ce94-11e0-b44a-9f094f73513e',
  );
  $terms[] = array(
    'uuid' => 'f76e7a4e-ce94-11e0-b44a-9f094f73513e',
    'name' => 'Education',
    'description' => '',
    'weight' => '11',
    'uuid_vocabulary' => 'f768ce04-ce94-11e0-b44a-9f094f73513e',
  );
  $terms[] = array(
    'uuid' => 'f76e8cba-ce94-11e0-b44a-9f094f73513e',
    'name' => 'Election News',
    'description' => '',
    'weight' => '12',
    'uuid_vocabulary' => 'f768ce04-ce94-11e0-b44a-9f094f73513e',
  );
  $terms[] = array(
    'uuid' => 'f76ea338-ce94-11e0-b44a-9f094f73513e',
    'name' => 'Ethics',
    'description' => '',
    'weight' => '13',
    'uuid_vocabulary' => 'f768ce04-ce94-11e0-b44a-9f094f73513e',
  );
  $terms[] = array(
    'uuid' => 'f76eb71c-ce94-11e0-b44a-9f094f73513e',
    'name' => 'Executive Power',
    'description' => '',
    'weight' => '14',
    'uuid_vocabulary' => 'f768ce04-ce94-11e0-b44a-9f094f73513e',
  );
  $terms[] = array(
    'uuid' => 'f76ecb79-ce94-11e0-b44a-9f094f73513e',
    'name' => 'Federal Legislation',
    'description' => '',
    'weight' => '15',
    'uuid_vocabulary' => 'f768ce04-ce94-11e0-b44a-9f094f73513e',
  );
  $terms[] = array(
    'uuid' => 'f76edfab-ce94-11e0-b44a-9f094f73513e',
    'name' => 'Finance',
    'description' => '',
    'weight' => '16',
    'uuid_vocabulary' => 'f768ce04-ce94-11e0-b44a-9f094f73513e',
  );
  $terms[] = array(
    'uuid' => 'f76ef2df-ce94-11e0-b44a-9f094f73513e',
    'name' => 'Foreign Policy',
    'description' => '',
    'weight' => '17',
    'uuid_vocabulary' => 'f768ce04-ce94-11e0-b44a-9f094f73513e',
  );
  $terms[] = array(
    'uuid' => 'f76f068d-ce94-11e0-b44a-9f094f73513e',
    'name' => 'Free Markets',
    'description' => '',
    'weight' => '18',
    'uuid_vocabulary' => 'f768ce04-ce94-11e0-b44a-9f094f73513e',
  );
  $terms[] = array(
    'uuid' => 'f76f1a09-ce94-11e0-b44a-9f094f73513e',
    'name' => 'Globalism',
    'description' => '',
    'weight' => '19',
    'uuid_vocabulary' => 'f768ce04-ce94-11e0-b44a-9f094f73513e',
  );
  $terms[] = array(
    'uuid' => 'f76f2ecf-ce94-11e0-b44a-9f094f73513e',
    'name' => 'Grassroots News',
    'description' => '',
    'weight' => '20',
    'uuid_vocabulary' => 'f768ce04-ce94-11e0-b44a-9f094f73513e',
  );
  $terms[] = array(
    'uuid' => 'f76f42a3-ce94-11e0-b44a-9f094f73513e',
    'name' => 'Health Freedom',
    'description' => '',
    'weight' => '21',
    'uuid_vocabulary' => 'f768ce04-ce94-11e0-b44a-9f094f73513e',
  );
  $terms[] = array(
    'uuid' => 'f76f581a-ce94-11e0-b44a-9f094f73513e',
    'name' => 'History',
    'description' => '',
    'weight' => '22',
    'uuid_vocabulary' => 'f768ce04-ce94-11e0-b44a-9f094f73513e',
  );
  $terms[] = array(
    'uuid' => 'f76f64fa-ce94-11e0-b44a-9f094f73513e',
    'name' => 'Just for Fun',
    'description' => '',
    'weight' => '23',
    'uuid_vocabulary' => 'f768ce04-ce94-11e0-b44a-9f094f73513e',
  );
  $terms[] = array(
    'uuid' => 'f76f74dc-ce94-11e0-b44a-9f094f73513e',
    'name' => 'Law',
    'description' => '',
    'weight' => '24',
    'uuid_vocabulary' => 'f768ce04-ce94-11e0-b44a-9f094f73513e',
  );
  $terms[] = array(
    'uuid' => 'f76f87bb-ce94-11e0-b44a-9f094f73513e',
    'name' => 'Media',
    'description' => '',
    'weight' => '25',
    'uuid_vocabulary' => 'f768ce04-ce94-11e0-b44a-9f094f73513e',
  );
  $terms[] = array(
    'uuid' => 'f76f9b25-ce94-11e0-b44a-9f094f73513e',
    'name' => 'Miscellany',
    'description' => '',
    'weight' => '26',
    'uuid_vocabulary' => 'f768ce04-ce94-11e0-b44a-9f094f73513e',
  );
  $terms[] = array(
    'uuid' => 'f76fac22-ce94-11e0-b44a-9f094f73513e',
    'name' => 'Monetary Policy',
    'description' => '',
    'weight' => '27',
    'uuid_vocabulary' => 'f768ce04-ce94-11e0-b44a-9f094f73513e',
  );
  $terms[] = array(
    'uuid' => 'f76fb8a4-ce94-11e0-b44a-9f094f73513e',
    'name' => 'Philosophy',
    'description' => '',
    'weight' => '28',
    'uuid_vocabulary' => 'f768ce04-ce94-11e0-b44a-9f094f73513e',
  );
  $terms[] = array(
    'uuid' => 'f76fc568-ce94-11e0-b44a-9f094f73513e',
    'name' => 'Presidential Race',
    'description' => '',
    'weight' => '29',
    'uuid_vocabulary' => 'f768ce04-ce94-11e0-b44a-9f094f73513e',
  );
  $terms[] = array(
    'uuid' => 'f76fd192-ce94-11e0-b44a-9f094f73513e',
    'name' => 'Rand Paul',
    'description' => '',
    'weight' => '30',
    'uuid_vocabulary' => 'f768ce04-ce94-11e0-b44a-9f094f73513e',
  );
  $terms[] = array(
    'uuid' => 'f76fdd9f-ce94-11e0-b44a-9f094f73513e',
    'name' => 'Republican Party',
    'description' => '',
    'weight' => '31',
    'uuid_vocabulary' => 'f768ce04-ce94-11e0-b44a-9f094f73513e',
  );
  $terms[] = array(
    'uuid' => 'f76fea2a-ce94-11e0-b44a-9f094f73513e',
    'name' => 'Revolution',
    'description' => '',
    'weight' => '32',
    'uuid_vocabulary' => 'f768ce04-ce94-11e0-b44a-9f094f73513e',
  );
  $terms[] = array(
    'uuid' => 'f76ff651-ce94-11e0-b44a-9f094f73513e',
    'name' => 'Ron Paul',
    'description' => '',
    'weight' => '33',
    'uuid_vocabulary' => 'f768ce04-ce94-11e0-b44a-9f094f73513e',
  );
  $terms[] = array(
    'uuid' => 'f7700275-ce94-11e0-b44a-9f094f73513e',
    'name' => 'Social Issues',
    'description' => '',
    'weight' => '34',
    'uuid_vocabulary' => 'f768ce04-ce94-11e0-b44a-9f094f73513e',
  );
  $terms[] = array(
    'uuid' => 'f7700e35-ce94-11e0-b44a-9f094f73513e',
    'name' => 'Socialism',
    'description' => '',
    'weight' => '35',
    'uuid_vocabulary' => 'f768ce04-ce94-11e0-b44a-9f094f73513e',
  );
  $terms[] = array(
    'uuid' => 'f7701a3d-ce94-11e0-b44a-9f094f73513e',
    'name' => 'State Legislation',
    'description' => '',
    'weight' => '36',
    'uuid_vocabulary' => 'f768ce04-ce94-11e0-b44a-9f094f73513e',
  );
  $terms[] = array(
    'uuid' => 'f770260e-ce94-11e0-b44a-9f094f73513e',
    'name' => 'Trade',
    'description' => '',
    'weight' => '37',
    'uuid_vocabulary' => 'f768ce04-ce94-11e0-b44a-9f094f73513e',
  );
  $terms[] = array(
    'uuid' => 'f77031f7-ce94-11e0-b44a-9f094f73513e',
    'name' => 'US Constitution',
    'description' => '',
    'weight' => '38',
    'uuid_vocabulary' => 'f768ce04-ce94-11e0-b44a-9f094f73513e',
  );
  $terms[] = array(
    'uuid' => 'f7703e0d-ce94-11e0-b44a-9f094f73513e',
    'name' => 'Video',
    'description' => '',
    'weight' => '39',
    'uuid_vocabulary' => 'f768ce04-ce94-11e0-b44a-9f094f73513e',
  );
  $terms[] = array(
    'uuid' => 'f7704adf-ce94-11e0-b44a-9f094f73513e',
    'name' => 'Voting',
    'description' => '',
    'weight' => '40',
    'uuid_vocabulary' => 'f768ce04-ce94-11e0-b44a-9f094f73513e',
  );
  $terms[] = array(
    'uuid' => 'f770588c-ce94-11e0-b44a-9f094f73513e',
    'name' => 'War and Military',
    'description' => '',
    'weight' => '41',
    'uuid_vocabulary' => 'f768ce04-ce94-11e0-b44a-9f094f73513e',
  );
  $terms[] = array(
    'uuid' => 'f770650c-ce94-11e0-b44a-9f094f73513e',
    'name' => 'World Affairs',
    'description' => '',
    'weight' => '42',
    'uuid_vocabulary' => 'f768ce04-ce94-11e0-b44a-9f094f73513e',
  );
  return $terms;
}
