<?php

include_once('piropublic_commerce.features.inc');

/**
 * Implementation of hook_nodeapi().
 */
function piropublic_commerce_nodeapi(&$node, $op, $a3 = NULL, $a4 = NULL) {
  if ($node->type=='product') {
  	switch ($op) {
      case 'view':
        if ($node->model=='D00001') {
          unset($node->content['model']);
          // manintain price update since moving to single-form
          //unset($node->content['display_price']);
          unset($node->content['sell_price']);
        }
      break;
    }
  }
}

/**
* Implements hook_uuid_node_features_export_render_alter()
*/
function piropublic_commerce_uuid_node_features_export_render_alter(&$export, $node, $module) {
  // don't allow uuid_features to export node properties that can change on deployment
  unset($export->changed);
  unset($export->created);
  unset($export->revision_uuid);
  unset($export->last_comment_timestamp);
  unset($export->revision_timestamp);
  unset($export->data);
  unset($export->picture);
  unset($export->old_status);
  unset($export->date);
  unset($export->webform);
  unset($export->location);
  unset($export->locations);
}
