<?php

include_once('piropublic_media.features.inc');

/**
 * Implementation of hook_init()
 */
function piropublic_media_init() {
  drupal_add_css(drupal_get_path('module', 'piropublic_media') . '/theme/css/piropublic_media.css');
  if (file_exists(drupal_get_path('module', 'piropublic_media') . '/theme/css/' . variable_get('theme_default', 'garland'). '.css')) {
    drupal_add_css(drupal_get_path('module', 'piropublic_media') . '/theme/css/' . variable_get('theme_default', 'garland'). '.css');
  }
}

/**
* Implements hook_uuid_node_features_export_render_alter()
*/
function piropublic_media_uuid_node_features_export_render_alter(&$export, $node, $module) {
  // don't allow uuid_features to export node properties that can change on deployment
  unset($export->changed);
  unset($export->created);
  unset($export->revision_uuid);
  unset($export->last_comment_timestamp);
  unset($export->revision_timestamp);
  unset($export->data);
  unset($export->picture);
  unset($export->old_status);
  unset($export->date);
  unset($export->webform);
  unset($export->location);
  unset($export->locations);

}