<?php

include_once('piropublic_media.features.inc');


/**
 * Implementation of hook_init()
 */
function piropublic_media_init() {
  drupal_add_css(drupal_get_path('module', 'piropublic_media') . '/theme/css/piropublic_media.css');
  if (file_exists(drupal_get_path('module', 'piropublic_media') . '/theme/css/' . variable_get('theme_default', 'garland'). '.css')) {
    drupal_add_css(drupal_get_path('module', 'piropublic_media') . '/theme/css/' . variable_get('theme_default', 'garland'). '.css');
  }
}

